### ISSUE TITLE
Build fails in happyhttp.cpp

### ISSUE THREAD

**Issue by glixx** [thp/numptyphysics#1]
happyhttp.cpp: In member function ‘void happyhttp::Connection::close()’:
happyhttp.cpp:283:3: error: ‘::close’ has not been declared
make: *** [happyhttp.o] Error 1

already fixed in:
http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=667302

#include <unistd.h>

**Comment by thp** [comment]
Fixed with the new codebase, now in the master branch.
