### ISSUE TITLE
Unable to read text

### ISSUE THREAD

**Issue by mfraser** [thp/numptyphysics#37]
Compiled 0.39 from git on Ubuntu 21.10, when I try to run it I am unable to see any text. 
![Screenshot_20220415_130116](https://user-images.githubusercontent.com/195323/163568489-a4905c07-fd33-427c-85f2-7780ff915aa9.png)

**Comment by thp** [comment]
@mfraser Maybe mention how you fixed it or what the issue was so other people running into the same issue know of a possible fix.

**Comment by mfraser** [comment]
> @mfraser Maybe mention how you fixed it or what the issue was so other people running into the same issue know of a possible fix.

I still had conflicting installs of various SDL packages from https://launchpad.net/~savoury1/+archive/ubuntu/multimedia even though he'd removed all packages for Ubuntu 21.04 & 21.10. Reverting back to the default versions fixed the issues.

**Comment by bawolk** [comment]
I just installed version 0.3.9 on Pop_OS 22.04 and am having exactly the same problem.  Also, the window is not resizable.

**Comment by thp** [comment]
> I just installed version 0.3.9 on Pop_OS 22.04 and am having exactly the same problem. Also, the window is not resizable.

What's the output of `dpkg -l | grep -i sdl` and do you have custom packages installed? Where/how did you install version 0.3.9 from?

**Comment by bawolk** [comment]
$ dpkg -l | grep -i sdl
ii  libsdl2-2.0-0:amd64                     2.0.20+dfsg-2build1                                             amd64        Simple DirectMedia Layer
ii  libsdl2-dev:amd64                       2.0.20+dfsg-2build1                                             amd64        Simple DirectMedia Layer development files
ii  libsdl2-image-2.0-0:amd64               2.0.5+dfsg1-3build1                                             amd64        Image loading library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-image-dev:amd64                 2.0.5+dfsg1-3build1                                             amd64        Image loading library for Simple DirectMedia Layer 2, development files
ii  libsdl2-ttf-2.0-0:amd64                 2.0.18+dfsg-2                                                   amd64        TrueType Font library for Simple DirectMedia Layer 2, libraries
ii  libsdl2-ttf-dev:amd64                   2.0.18+dfsg-2                                                   amd64        TrueType Font library for Simple DirectMedia Layer 2, development files

I downloaded it from github/thp

**Comment by thp** [comment]
> I downloaded it from github/thp

0.3.10 should have this particular issue fixed, please download the new version.
