### ISSUE TITLE
Merge with smr99's fork

### ISSUE THREAD

**Issue by glixx** [thp/numptyphysics#8]
Please merge your code with smr99's fork: https://github.com/smr99/numptyphysics
He has a lot of levels: https://github.com/smr99/numptyphysics/tree/master/data/NP-complete and other usefull modifications.

**Comment by thp** [comment]
It's not so easy, @smr99's fork is from an older branch. My repo also contains all the NP-complete levels, and his codebase still depends mostly on SDL while my codebase builds on top of GL (and theoretically can support any rendering backend that implements the interface defined in `Renderer.h`).

There would be some useful changes from his branch, but they would need to be separated out and submitted separately as a pull request, I'd be happy to review and merge them.

**Comment by glixx** [comment]
He had activity 1 year ago.

**Comment by thp** [comment]
Yeah, the repository here has activity in April this year, but that alone isn't any metric to go by.

From a quick scroll through his commit list, maybe the upgrade to the newer Box2D release might be worth merging. Other things such as replacing Array with std::vector have already been done in my repo (and if you look at the timestamps of the commits, even earlier than in the other repository).

If you can list the commits that you want to have merged from @smr99's repository, I'm happy to have a look at them.

Again, both branches diverged from each other, and some fixes have been done to both repositories while others have been done differently (he seems to have ported it to SDL2, which is supported - among other platform abstractions - in my repo as well). Also, my codebase requires OpenGL with programmable shader pipeline, but one could theoretically write a Renderer subclass that doesn't depend on OpenGL, if one is so inclined.

**Comment by glixx** [comment]
Yes, his fork went by other way. Thank you for checking his commits.
The best way is to work together - you and smr99.
Please merge maximum useful stuff by your opinion: for example new Box2D.
Thanks again.

**Comment by thp** [comment]
Feel free to open separate pull requests for any changes you want to have merged.

**Comment by smr99** [comment]
At the time I made my fork, I wasn't aware that Thomas was still updating the code.  I was initially motivated to fix problems I saw in the Debian release, later to update the library requirements (bullet, SDL).  I'm sure I made choices that Thomas disagrees with but all my code is here on github for anyone to cherry-pick.  I myself haven't touched this is quite some time and it is unlikely that I will do so in the near future.  So @glixx: it may be up to you!

Cheers,
-Steve

**Comment by glixx** [comment]
@smr99, will you work together with @thp? Will you find total solution without fork? I want to see numptyphysics actively development, localized. I can help with translators if you will add i18n support.
@smr99, will you create pull requests based on the latest @thp's commit?
Thanks for your interest.

**Comment by thp** [comment]
@glixx I guess the point of @smr99 (and my point as well) was that if you want to have things merged, find the commits and create merge requests yourself. We will not be doing your work there. If you want to get things done, do them yourself.

I'll be happy to review/merge any merge requests, but don't have time or interest to go patch hunting myself. End of topic here.

**Comment by thp** [comment]
Closing discussion. Please create actual merge requests if you want to get something done here, don't expect us to do it for you.
